alertmanager:
  alertmanagerSpec:
    secrets:
      - pagerduty-secret

  config:
    global:
      resolve_timeout: 5m

    route:
      group_by:
        - alertname
        - namespace
        - service

      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h

      receiver: default

      routes:
        - matchers:
            - severity = "critical"
          receiver: pagerduty

    receivers:

      - name: default

      - name: pagerduty

        pagerduty_configs:
          - routing_key_file: /etc/alertmanager/secrets/pagerduty-secret/integration-key
            send_resolved: true